// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/generate_png.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/manifest.json.ts";
import * as $5 from "./routes/service_worker.js.ts";
import * as $$0 from "./islands/Form.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/joke.ts": $1,
    "./routes/generate_png.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/manifest.json.ts": $4,
    "./routes/service_worker.js.ts": $5,
  },
  islands: {
    "./islands/Form.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
